"""empty message

Revision ID: b3a0c562dd5c
Revises: 11ffc0c93e6f
Create Date: 2022-08-24 21:45:36.101877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3a0c562dd5c'
down_revision = '11ffc0c93e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatrooms', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'chatrooms', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chatrooms', type_='foreignkey')
    op.drop_column('chatrooms', 'creator_id')
    # ### end Alembic commands ###
