"""empty message

Revision ID: 0b1133e023a0
Revises: 952f71733fba
Create Date: 2022-08-24 21:02:36.717830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b1133e023a0'
down_revision = '952f71733fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatrooms', sa.Column('recipient_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'chatrooms', 'users', ['recipient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chatrooms', type_='foreignkey')
    op.drop_column('chatrooms', 'recipient_id')
    # ### end Alembic commands ###
